name: Build C++ Project

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Native Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev

      - name: Export GitHub Actions Cache Parameters
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('VCPKG_BINARY_SOURCES', 'clear;x-gha,readwrite');

      - name: Configure and Build
        shell: bash
        env:
          ACTIONS_CACHE_URL: ${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
             cmake -B build -S . \
               -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" \
               -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_CXX_FLAGS="/permissive-"
          else
             cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
          fi
          cmake --build build --config Release
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electronic-shield-door-${{ matrix.os }}

          path: |
            build/Release/
            build/door_opener
          if-no-files-found: warn
          
